/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fms.interfaces;

import fms.data.FlightDataManager;
import fms.model.Destination;
import fms.model.Flight;
import fms.model.Plane;
import fms.model.Schedule;

public class AdminDashboard extends javax.swing.JFrame {
    private String registeredAdmin;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(String adminName) {
        initComponents();
        
        loadDashboardData();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); 

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                FlightDataManager.getInstance().saveAllData();
                System.exit(0); 
            }
        });
        
        createFlightPanel.setVisible(false);
        changePlanePanel.setVisible(false);
            
        this.registeredAdmin = adminName;
        
        welcomeLabel.setText("Welcome, " + adminName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminActionsGroup = new javax.swing.ButtonGroup();
        welcomeLabel = new javax.swing.JLabel();
        adminDashboardTitle = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        changePlaneButton = new javax.swing.JRadioButton();
        createFlightButton = new javax.swing.JRadioButton();
        createFlightPanel = new javax.swing.JPanel();
        enterFlightDetailsText = new javax.swing.JLabel();
        destinationCombo = new javax.swing.JComboBox<>();
        createPlaneCombo = new javax.swing.JComboBox<>();
        scheduleDayCombo = new javax.swing.JComboBox<>();
        scheduleTimeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scheduleDayLabel = new javax.swing.JLabel();
        scheduleTimeLabel = new javax.swing.JLabel();
        saveFlightButton = new javax.swing.JButton();
        initialSeatsField = new javax.swing.JTextField();
        initialSeatsLabel = new javax.swing.JLabel();
        changePlanePanel = new javax.swing.JPanel();
        chooseFlightText = new javax.swing.JLabel();
        flightCombo = new javax.swing.JComboBox<>();
        choosePlaneText = new javax.swing.JLabel();
        planeCombo = new javax.swing.JComboBox<>();
        confirmPlaneChangeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        viewFlightsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome");

        adminDashboardTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminDashboardTitle.setText("Admin Dashboard");

        jLabel1.setText("What would you like to do?");

        adminActionsGroup.add(changePlaneButton);
        changePlaneButton.setText("Change flight's plane");
        changePlaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePlaneButtonActionPerformed(evt);
            }
        });

        adminActionsGroup.add(createFlightButton);
        createFlightButton.setText("Create flight");
        createFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePlaneButton)
                    .addComponent(createFlightButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createFlightButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePlaneButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        enterFlightDetailsText.setText("Enter flight's details");

        destinationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        createPlaneCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        scheduleDayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        scheduleDayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleDayComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Destination");

        jLabel3.setText("Plane");

        scheduleDayLabel.setText("Day");

        scheduleTimeLabel.setText("Time (HH:MM:SS)");

        saveFlightButton.setText("Submit");
        saveFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFlightButtonActionPerformed(evt);
            }
        });

        initialSeatsField.setText("0");
        initialSeatsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialSeatsFieldActionPerformed(evt);
            }
        });

        initialSeatsLabel.setText("Seats (Optional)");

        javax.swing.GroupLayout createFlightPanelLayout = new javax.swing.GroupLayout(createFlightPanel);
        createFlightPanel.setLayout(createFlightPanelLayout);
        createFlightPanelLayout.setHorizontalGroup(
            createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createFlightPanelLayout.createSequentialGroup()
                .addGroup(createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createFlightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createFlightPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3))
                            .addGroup(createFlightPanelLayout.createSequentialGroup()
                                .addComponent(destinationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(createPlaneCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createFlightPanelLayout.createSequentialGroup()
                                .addComponent(enterFlightDetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(createFlightPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scheduleDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scheduleDayLabel))
                                .addGap(39, 39, 39)
                                .addGroup(createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(scheduleTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scheduleTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(initialSeatsLabel)
                                    .addComponent(initialSeatsField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(createFlightPanelLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(saveFlightButton)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        createFlightPanelLayout.setVerticalGroup(
            createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createFlightPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(enterFlightDetailsText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(scheduleDayLabel)
                    .addComponent(scheduleTimeLabel)
                    .addComponent(initialSeatsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scheduleDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createPlaneCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initialSeatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveFlightButton)
                .addContainerGap())
        );

        chooseFlightText.setText("Choose flight:");

        flightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        choosePlaneText.setText("Choose plane:");

        planeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        confirmPlaneChangeButton.setText("Submit");
        confirmPlaneChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPlaneChangeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changePlanePanelLayout = new javax.swing.GroupLayout(changePlanePanel);
        changePlanePanel.setLayout(changePlanePanelLayout);
        changePlanePanelLayout.setHorizontalGroup(
            changePlanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePlanePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(changePlanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chooseFlightText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(changePlanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choosePlaneText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planeCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(changePlanePanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(confirmPlaneChangeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changePlanePanelLayout.setVerticalGroup(
            changePlanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePlanePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changePlanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseFlightText)
                    .addComponent(choosePlaneText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(changePlanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmPlaneChangeButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        backButton.setText("< Back");
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        viewFlightsButton.setText("View Flights");
        viewFlightsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFlightsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewFlightsButton)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminDashboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(changePlanePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(createFlightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(viewFlightsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminDashboardTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(createFlightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePlanePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFlightButtonActionPerformed
        // TODO add your handling code here:
        if (createFlightButton.isSelected()) {
            createFlightPanel.setVisible(true);
            changePlanePanel.setVisible(false);
        }
    }//GEN-LAST:event_createFlightButtonActionPerformed

    private void changePlaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePlaneButtonActionPerformed
        // TODO add your handling code here:
        if (changePlaneButton.isSelected()) {
            createFlightPanel.setVisible(false);
            changePlanePanel.setVisible(true);
        }
    }//GEN-LAST:event_changePlaneButtonActionPerformed

    private void scheduleDayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleDayComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleDayComboActionPerformed

    private void saveFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFlightButtonActionPerformed
        // TODO add your handling code here:
        FlightDataManager manager = FlightDataManager.getInstance();
        
        try {
            String selectedDestinationName = (String) destinationCombo.getSelectedItem();
            String selectedPlaneDetails = (String) createPlaneCombo.getSelectedItem();
            String day = (String) scheduleDayCombo.getSelectedItem();
            String timeStr = scheduleTimeField.getText();
            String seatsStr = initialSeatsField.getText();
            
            if (selectedDestinationName == null || selectedPlaneDetails == null || day == null || timeStr.isEmpty()) {
                throw new IllegalArgumentException("All fields must be selected/filled.");
            }
            
            int initialSeats = Integer.parseInt(seatsStr.trim());
            
            String planeName;
            int index = selectedPlaneDetails.indexOf(" (");
            if (index != -1) {
                planeName = selectedPlaneDetails.substring(0, index);
            } else {
                planeName = selectedPlaneDetails; 
            }
            Plane plane = manager.getPlaneByName(planeName);
            Destination destination = manager.getDestinationByName(selectedDestinationName);
            Schedule schedule = new Schedule(day, java.sql.Time.valueOf(timeStr));
            
            if (plane == null || destination == null) {
                throw new RuntimeException("Error fetching Plane or Destination.");
            }
            
            if (initialSeats < 0 || initialSeats > plane.getCapacity()) {
                throw new IllegalArgumentException("Initial seats taken (" + initialSeats + 
                                                   ") must be between 0 and plane capacity (" + 
                                                   plane.getCapacity() + ").");
            }
            
            if (initialSeats == 0) {
                manager.addFlight(plane, schedule, destination);
            } else {
                manager.addFlight(plane, schedule, destination, initialSeats);
            }
            
            javax.swing.JOptionPane.showMessageDialog(this, "Flight to " + destination.getName() + " created successfully!");
            
            scheduleTimeField.setText("");
            loadDashboardData();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Flight Number or Time format (use HH:MM:SS).");
        } catch (RuntimeException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_saveFlightButtonActionPerformed

    private void confirmPlaneChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPlaneChangeButtonActionPerformed
        // TODO add your handling code here:
        FlightDataManager manager = FlightDataManager.getInstance();

        String selectedFlightDetail = (String) flightCombo.getSelectedItem();
        String selectedNewPlaneDetail = (String) planeCombo.getSelectedItem();

        if (selectedFlightDetail == null || selectedNewPlaneDetail == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select both a flight and a new plane.");
            return;
        }

        try {
            int flightNumber = Integer.parseInt(selectedFlightDetail.split(" ")[0]);
            String newPlaneModel = selectedNewPlaneDetail.split(" ")[0]; 

            Plane newPlane = manager.getPlaneByName(newPlaneModel);

            if (newPlane == null) {
                 throw new RuntimeException("Selected plane not found.");
            }

            boolean success = manager.changeFlightPlane(flightNumber, newPlane);

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Plane for Flight " + flightNumber + " successfully changed to " + newPlaneModel + ".");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "ERROR: Cannot change plane. The new plane's capacity is lower than the current bookings.");
            }

            loadDashboardData(); 

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Internal error parsing flight number.");
        } catch (RuntimeException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Operation failed: " + e.getMessage());
        }
    }//GEN-LAST:event_confirmPlaneChangeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        FlightDataManager.getInstance().saveAllData(); 

        fms.utils.interfaceUtils.openRegisterUI(this);
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewFlightsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFlightsButtonActionPerformed
        // TODO add your handling code here:
        fms.utils.interfaceUtils.openFlightInfoDisplay(this);
    }//GEN-LAST:event_viewFlightsButtonActionPerformed

    private void initialSeatsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialSeatsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialSeatsFieldActionPerformed

    private void loadDashboardData() {
        FlightDataManager manager = FlightDataManager.getInstance();

        // 1. Populate Destination Combo
        destinationCombo.removeAllItems();
        for (Destination dest : manager.getDestinations()) {
            destinationCombo.addItem(dest.getName());
        }

        // 2. Populate Plane Combos
        planeCombo.removeAllItems();
        createPlaneCombo.removeAllItems(); 
        for (Plane plane : manager.getPlanes()) {
            String planeDetail = plane.getName() + " (" + plane.getCapacity() + " seats)";
            planeCombo.addItem(planeDetail);
            createPlaneCombo.addItem(planeDetail);
        }

        // 3. Populate Flight Combo
        flightCombo.removeAllItems();
        for (Flight flight : manager.getFlights()) {
            String flightDetail = flight.getFlightNumber() + " to " + flight.getDestination().getName();
            flightCombo.addItem(flightDetail);
        }

        // 4. Populate Schedule/Day Combo
        scheduleDayCombo.removeAllItems();
        scheduleDayCombo.addItem("Monday");
        scheduleDayCombo.addItem("Tuesday");
        scheduleDayCombo.addItem("Wednesday");
        scheduleDayCombo.addItem("Thursday");
        scheduleDayCombo.addItem("Friday");
        scheduleDayCombo.addItem("Saturday");
        scheduleDayCombo.addItem("Sunday");
        // ... add other days
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.ButtonGroup adminActionsGroup;
    private javax.swing.JLabel adminDashboardTitle;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton changePlaneButton;
    private javax.swing.JPanel changePlanePanel;
    private javax.swing.JLabel chooseFlightText;
    private javax.swing.JLabel choosePlaneText;
    private javax.swing.JButton confirmPlaneChangeButton;
    private javax.swing.JRadioButton createFlightButton;
    private javax.swing.JPanel createFlightPanel;
    private javax.swing.JComboBox<String> createPlaneCombo;
    private javax.swing.JComboBox<String> destinationCombo;
    private javax.swing.JLabel enterFlightDetailsText;
    private javax.swing.JComboBox<String> flightCombo;
    private javax.swing.JTextField initialSeatsField;
    private javax.swing.JLabel initialSeatsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> planeCombo;
    private javax.swing.JButton saveFlightButton;
    private javax.swing.JComboBox<String> scheduleDayCombo;
    private javax.swing.JLabel scheduleDayLabel;
    private javax.swing.JTextField scheduleTimeField;
    private javax.swing.JLabel scheduleTimeLabel;
    private javax.swing.JButton viewFlightsButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
