/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fms.interfaces;

import fms.data.FlightDataManager;

public class CustomerDashboard extends javax.swing.JFrame {
    private String registeredCustomer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerDashboard.class.getName());

    /**
     * Creates new form CustomerDashboard
     */
    public CustomerDashboard(String customerName) {
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); 

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                FlightDataManager.getInstance().saveAllData();
                System.exit(0); 
            }
        });
        
        loadDestinations();
        
        this.registeredCustomer = customerName;
        
        welcomeLabel.setText("Welcome, " + customerName);
    }
    
    private void loadDestinations() {
        FlightDataManager manager = FlightDataManager.getInstance();
        destinationCombo.removeAllItems();
        destinationCombo.addItem("--- Select Destination ---");

        java.util.Set<String> uniqueDestinations = new java.util.HashSet<>();
        for (fms.model.Destination dest : manager.getDestinations()) {
            uniqueDestinations.add(dest.getName());
        }

        for (String city : uniqueDestinations) {
            destinationCombo.addItem(city);
        }

        flightCombo.removeAllItems();
        flightCombo.addItem("--- Select a Flight ---");
        flightCombo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        destinationCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        flightCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        bookFlightSubmitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        extraLuggageCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Customer Dashboard");

        welcomeLabel.setText("Welcome");

        jLabel2.setText("Choose your destination:");

        destinationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        destinationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(destinationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(destinationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        flightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Pick a flight:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(flightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(flightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        bookFlightSubmitButton.setText("Submit");
        bookFlightSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightSubmitButtonActionPerformed(evt);
            }
        });

        backButton.setText("< Back");
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        extraLuggageCheckBox.setText("Extra luggage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(bookFlightSubmitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(extraLuggageCheckBox)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(extraLuggageCheckBox)
                .addGap(22, 22, 22)
                .addComponent(bookFlightSubmitButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destinationComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationComboActionPerformed
        // TODO add your handling code here:
        String selectedDestination = (String) destinationCombo.getSelectedItem();
        flightCombo.removeAllItems();

        if (selectedDestination == null || selectedDestination.contains("Select Destination")) {
            flightCombo.addItem("--- Select a Flight ---");
            flightCombo.setEnabled(false);
            return;
        }

        FlightDataManager manager = FlightDataManager.getInstance();

        for (fms.model.Flight flight : manager.getFlights()) {
            // Check if the flight goes to the selected destination
            if (flight.getDestination().getName().equals(selectedDestination)) {
                // Check if there are seats available
                int available = flight.getPlane().getCapacity() - flight.getSeatsTaken();

                if (available > 0) {
                    // Format the display string: "Flight # [Day, Time] (Available seats)"
                    String display = String.format("Flight %d - %s, %s (%d seats)", 
                        flight.getFlightNumber(), 
                        flight.getSchedule().getDay(), 
                        flight.getSchedule().getTime().toString().substring(0, 5), // Show HH:MM
                        available
                    );
                    flightCombo.addItem(display);
                }
            }
        }

        if (flightCombo.getItemCount() > 0) {
            flightCombo.setEnabled(true);
        } else {
            flightCombo.addItem("No available flights found.");
            flightCombo.setEnabled(false);
        }
    }//GEN-LAST:event_destinationComboActionPerformed

    private void bookFlightSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightSubmitButtonActionPerformed
        // TODO add your handling code here:
        String selectedFlightDetail = (String) flightCombo.getSelectedItem();

        if (selectedFlightDetail == null || selectedFlightDetail.contains("No available flights") || selectedFlightDetail.contains("Select a Flight")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an available flight first.");
            return;
        }

        try {
            String[] parts = selectedFlightDetail.split(" ");
            int flightNumber = Integer.parseInt(parts[1]); 

            boolean success = FlightDataManager.getInstance().attemptBookFlight(flightNumber, extraLuggageCheckBox.isSelected());

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Booking successful! You are now on Flight " + flightNumber + " to " + (String)destinationCombo.getSelectedItem() + ".",
                    "Success", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );

                destinationComboActionPerformed(null); 

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Booking failed. This flight may have just been fully booked.", 
                    "Flight Full", 
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
            }

        } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Internal error: Could not determine flight number.");
            logger.log(java.util.logging.Level.SEVERE, "Error parsing flight number: " + selectedFlightDetail, e);
        }
    }//GEN-LAST:event_bookFlightSubmitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        FlightDataManager.getInstance().saveAllData(); 

        fms.utils.interfaceUtils.openRegisterUI(this);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerDashboard("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookFlightSubmitButton;
    private javax.swing.JComboBox<String> destinationCombo;
    private javax.swing.JCheckBox extraLuggageCheckBox;
    private javax.swing.JComboBox<String> flightCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
