/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fms.interfaces;

import fms.data.FlightDataManager;
import fms.model.Flight;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;

/**
 *
 * @author GIDEON
 */
public class FlightInformationUI extends javax.swing.JFrame {
    
//    private javax.swing.JTextArea flightInfoArea;
    private javax.swing.JTable flightTable;
    private DefaultTableModel tableModel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlightInformationUI.class.getName());

    /**
     * Creates new form FlightInformationUI
     */
    public FlightInformationUI() {
        initComponents();
        
        getContentPane().setLayout(new java.awt.BorderLayout());
        
        String[] columnNames = {"Flight No.", "Destination", "Day", "Time", "Available Seats", "Plane Model"};
        
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        flightTable = new JTable(tableModel);
        
        javax.swing.JScrollPane infoScrollPane = new JScrollPane(flightTable);
        
        infoScrollPane.setPreferredSize(new java.awt.Dimension(800, 300));
        
        getContentPane().add(infoScrollPane, BorderLayout.CENTER);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        flightTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        loadFlightData();
        pack();
        setLocationRelativeTo(null);
    }
    
//    private void loadFlightData() {
//        FlightDataManager manager = FlightDataManager.getInstance();
//        List<Flight> flights = manager.getFlights();
//        
//        StringBuilder sb = new StringBuilder();
//        
//        sb.append(String.format("%-10s | %-15s | %-10s | %-10s | %-10s | %s\n", 
//                "Flight #", "Destination", "Day", "Time", "Available Seats", "Plane Model"));
//        sb.append("--------------------------------------------------------------------------------------------------\n");
//        
//        for (Flight flight : flights) {
//            int availableSeats = flight.getPlane().getCapacity() - flight.getSeatsTaken();
//            
//            sb.append(String.format("%-10d | %-15s | %-10s | %-10s | %-10d | %s\n", 
//                flight.getFlightNumber(), 
//                flight.getDestination().getName(), 
//                flight.getSchedule().getDay(),
//                flight.getSchedule().getTime().toString().substring(0, 5),
//                availableSeats,
//                flight.getPlane().getName()));
//        }
//        
//        flightInfoArea.setText(sb.toString());
//    }
    
    private void loadFlightData() {
        tableModel.setRowCount(0);

        FlightDataManager manager = FlightDataManager.getInstance();
        List<Flight> flights = manager.getFlights();

        for (Flight flight : flights) {
            int availableSeats = flight.getPlane().getCapacity() - flight.getSeatsTaken();

            Object[] rowData = new Object[] {
                flight.getFlightNumber(),
                flight.getDestination().getName(),
                flight.getSchedule().getDay(),
                flight.getSchedule().getTime().toString().substring(0, 5), // HH:MM
                availableSeats,
                flight.getPlane().getName()
            };

            tableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlightInformationUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
