/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fms.interfaces;

import fms.data.FlightDataManager;
import fms.model.Flight;
import java.awt.BorderLayout;
import java.util.List;

/**
 *
 * @author GIDEON
 */
public class FlightInformationUI extends javax.swing.JFrame {
    
    private javax.swing.JTextArea flightInfoArea;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlightInformationUI.class.getName());

    /**
     * Creates new form FlightInformationUI
     */
    public FlightInformationUI() {
        initComponents();
        
        getContentPane().setLayout(new java.awt.BorderLayout());
        
        flightInfoArea = new javax.swing.JTextArea(20, 50);
        flightInfoArea.setEditable(false);
        javax.swing.JScrollPane infoScrollPane = new javax.swing.JScrollPane(flightInfoArea);
        
        getContentPane().add(infoScrollPane, BorderLayout.CENTER);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        loadFlightData();
        pack();
        setLocationRelativeTo(null);
    }
    
    private void loadFlightData() {
        FlightDataManager manager = FlightDataManager.getInstance();
        List<Flight> flights = manager.getFlights();
        
        StringBuilder sb = new StringBuilder();
        
        sb.append(String.format("%-10s | %-15s | %-10s | %-10s | %-10s | %s\n", 
                "Flight #", "Destination", "Day", "Time", "Seats", "Plane Model"));
        sb.append("--------------------------------------------------------------------------------------------------\n");
        
        for (Flight flight : flights) {
            int availableSeats = flight.getPlane().getCapacity() - flight.getSeatsTaken();
            
            sb.append(String.format("%-10d | %-15s | %-10s | %-10s | %-10d | %s\n", 
                flight.getFlightNumber(), 
                flight.getDestination().getName(), 
                flight.getSchedule().getDay(),
                flight.getSchedule().getTime().toString().substring(0, 5),
                availableSeats,
                flight.getPlane().getName()));
        }
        
        flightInfoArea.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlightInformationUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
